name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Hi Bhanu..."
  clone-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repos
        uses: actions/checkout@v4
        with:
          repository: BhanupriyaH/test
          path: master

      - name: get Branch
        run: |
          export BRANCHES=$(git branch -r)
          echo $BRANCHES | grep main
