name: hello-world
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'GitHub Repo Name'
        required: true
        default: 'BhanupriyaH/test'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Hi Bhanu..."
  clone-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repos
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo-name }}
          path: test

      - name: get Branch
        run: |
          cd test
          export BRANCHES=$(git branch -r)
          echo $BRANCHES
