name: hello-world
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'GitHub Repo Name'
        required: true
        default: 'BhanupriyaH/test'
jobs:
  loopcheck:
    strategy:
      matrix:
        repo_names: [BhanupriyaH/test,BhanupriyaH/parent]
    runs-on: ubuntu-latest
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: print output
        run: echo ${{ matrix.repo_names}}
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Hi Bhanu..."
  clone-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repos
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo-name }}
          path: test

      - name: get Branch
        run: |
          cd test
          export BRANCHES=$(git branch -r)
          echo $BRANCHES
      
      - name: Mendax Loop through numbers
        id: loop
        run: |
          for i in 1 2 3 4 5
          do
            echo "Mendax Current number: $i"
          done
