name: check if branch exists
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'GitHub Repo Name'
        required: false
        default: 'BhanupriyaH/test'
jobs:
  loopcheck:
      strategy:
        matrix:
          repo_names: [BhanupriyaH/test,BhanupriyaH/parent]
      runs-on: ubuntu-latest
      steps:
        - name: print output
          run: echo ${{ matrix.repo_names}}
        - name: Checkout repos
          uses: actions/checkout@v4
          with:
            repository: ${{ matrix.repo_names}}
            fetch-depth: 0
        - name: get Branch
          run: git branch -r | grep main
  test-for-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Mendax Loop through numbers
        id: loop
        run: |
          for i in 1 2 3 4 5
          do
            echo "Mendax Current number: $i"
          done
