name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Hi Bhanu..."
  clone-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
          
      - name: Checkout other repos
        uses: actions/checkout@v4
        with:
          repository: BhanupriyaH/test
          path: master
